# Sets the theme: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
theme: jekyll-theme-hacker
title: Computing Notebook
markdown: rdiscount
